### ISSUE TITLE
Trigger not created

### ISSUE THREAD

**Issue by trondhindenes** [matt-filion/serverless-external-s3-event#14]
I have the following serverless yaml:
```
service: serverlesstest # NOTE: update this with your service name
plugins:
 - serverless-external-s3-event

provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "*"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::trondserverlesstest"
functions:
  hello:
    handler: handler.hello
    events:
      - existingS3:
          bucket: trondserverlesstest
          event: 
            - s3:ObjectCreated:*
```

This deploys fine, thanks to the s3 event plugin, but the produced lambda function in aws has a blank trigger, so it's not actually wired up.
Running serverless version:
`1.7.0`

**Comment by trondhindenes** [comment]
Also tried with serverless `1.10.2` with the same results

**Comment by trondhindenes** [comment]
okay, so I noticed at the bottom there's a separate `s3deploy` command. However, when trying that, I get:
```
> sls s3deploy --stage dev
Attaching event(s) to: trondserverlesstest
Error attaching event(s) Unable to validate the following destination configurations
```

Not much to go by here. I've tested the iamrole in the simulator, and everything checks out. I also had an error in my serverless yaml, which has been corrected. It now reads:
```
service: serverlesstest
plugins:
 - serverless-external-s3-event

provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "*"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::trondserverlesstest"
functions:
  hello:
    handler: handler.hello
    events:
      - existingS3:
          bucket: trondserverlesstest
          event: 
            - s3:ObjectCreated:*
```

I'm a bit stumped, setting the sls debug level doesn't produce any output either.

**Comment by stephanechauvin** [comment]
Same problem here... 

Here is my full serverless file  :

~~~yaml
service: tests3externalevent

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-central-1
  iamRoleStatements:    
    -  Effect: "Allow"
       Action:
         - "s3:PutBucketNotification"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::keinfeuzikajnfeziu"

functions:
  myfunction:
    handler: handler.test
    events:
      - existingS3:
          bucket: keinfeuzikajnfeziu
          events:
            - s3:ObjectCreated:*

plugins:
  - serverless-external-s3-event
~~~

I guess we are doing something wrong, as this is a very basic config...

thanks in advance

**Comment by duckworth** [comment]
I am troubleshooting the same issue. It looks like in lambdaPermApi it is trying to hit AWS with a .request('Lambda', 'getPolicy') call and failing with a 404 because there is no policy defined on the Lambda.

**Comment by duckworth** [comment]
I added a pull request https://github.com/matt-filion/serverless-external-s3-event/pull/15 to handle this and it is working locally. It was also mentioned in https://github.com/matt-filion/serverless-external-s3-event/issues/13

**Comment by matt-filion** [comment]
This should be resolved with 2.0 branch as well as 1.0.6, which was just pushed to NPM. 2.0 I'll wait to push until I get some confirmation from others that it works for them as expected.

**Comment by justinmchase** [comment]
I'm using 1.0.6 and am still experiencing this issue. I am getting:

> Unable to validate the following destination configurations

```
- existingS3:
    bucket: example
    events:
      - s3:ObjectCreated:*
    rules:
      - prefix: uploads
      - suffix: .gz
```

**Comment by matt-filion** [comment]
@justinmchase Are you able to give 2.0~ a try and see if it resolves this issue for you?

**Comment by PiotrFras** [comment]
Same issue here, no trigger created.

Serverless: 1.17.0
Plugin: serverless-external-s3-event@1.0.7

**Comment by matt-filion** [comment]
@PiotrFras Can you try the 2.0 version and see if that resoles your issue.

**Comment by matt-filion** [comment]
This issue is stale, closing.

**Comment by bkarakashev** [comment]
Is this resolved?
I am still having the issue.

It works for all my other Lambda that are using NodeJS but doesn't work for the Python one....

**Comment by kittrCZ** [comment]
@matt-filion I'm still seeing this issue, here is the config:

```
provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::${self:custom.bucket}"

functions:
  func:
    handler: handler.func
    runtime: nodejs6.10
    memory: 128
    timeout: 30
    events:
      - existingS3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: func/
```

Do we have resolution for this?

**Comment by malcyL** [comment]
I've started seeing this error today.

Interestingly - it's failing on a CI build server for the master build that has been passing previously.

I wonder if there is a race condition in the creation of some of the resources. 
See https://github.com/awslabs/serverless-application-model/issues/184
